spring.application.name=API-Gateway
server.port=9739
spring.cloud.config.enabled=false

resilience4j.retry.instances.API-Gateway.max-attempts=5
resilience4j.retry.instances.API-Gateway.wait-duration=2s

spring.cloud.gateway.server.webflux.routes[0].id=Admin-Service
spring.cloud.gateway.server.webflux.routes[0].uri=http://localhost:8078
spring.cloud.gateway.server.webflux.routes[0].predicates[0]=Path=/api/admin/**

spring.cloud.gateway.server.webflux.routes[1].id=Audit-Service
spring.cloud.gateway.server.webflux.routes[1].uri=http://localhost:8085
spring.cloud.gateway.server.webflux.routes[1].predicates[0]=Path=/audit/**

spring.cloud.gateway.server.webflux.routes[2].id=FleetRegistryService
spring.cloud.gateway.server.webflux.routes[2].uri=http://localhost:8095
spring.cloud.gateway.server.webflux.routes[2].predicates[0]=Path=/routes/**,/schedules/**,/vehicles/**

spring.cloud.gateway.server.webflux.routes[3].id=DriverLogService
spring.cloud.gateway.server.webflux.routes[3].uri=http://localhost:9091
spring.cloud.gateway.server.webflux.routes[3].predicates[0]=Path=/assignments/**,/drivers/**,/trips/**

spring.cloud.gateway.server.webflux.routes[4].id=Shipment-Service
spring.cloud.gateway.server.webflux.routes[4].uri=http://localhost:8096
spring.cloud.gateway.server.webflux.routes[4].predicates[0]=Path=/api/shipment/**

spring.cloud.gateway.server.webflux.routes[5].id=Delivery_Proof-of-recepit-Service
spring.cloud.gateway.server.webflux.routes[5].uri=http://localhost:8099
spring.cloud.gateway.server.webflux.routes[5].predicates[0]=Path=/api/delivery/**

spring.cloud.gateway.server.webflux.routes[6].id=Inspection_Maintenance-Service
spring.cloud.gateway.server.webflux.routes[6].uri=http://localhost:9093
spring.cloud.gateway.server.webflux.routes[6].predicates[0]=Path=/maintenance/**,/inspections/**


spring.cloud.gateway.server.webflux.routes[7].id=Reporting-Analytics-Service
spring.cloud.gateway.server.webflux.routes[7].uri=http://localhost:8087
spring.cloud.gateway.server.webflux.routes[7].predicates[0]=Path=/api/reporting/**
